server:
  port: 8085
  servlet:
    context-path: /mspago
    
spring:
  application:
    name: ms-pago
  jpa:
    properties:
      hibernate:
        temp:                                                                                                                               
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect    
    
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka