server:
  port: 8081
  servlet:
    context-path: /msconsulta
    
spring:
  application:
    name: ms-consulta
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect    
    