server:
  port: 8082
  servlet:
    context-path: /msconsulta
    
spring:
  application:
    name: ms-consulta
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect    
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka